Add stub for new exercise: sum-of-multiples
exercism/dart pull request #466
Opened 2022-11-14 12:00 UTC by kytrinyx

This is a proposal for a new exercise based on the canonical data in the problem-specifications repository.

I didn't make any design choices whatsoever—if you think a different API would be better suited to this exercise, please suggest some changes, and I will regenerate the test suite.

I put myself as contributor rather than author, since I don't intend to write the example solution.
As such, the authorship of this exercise is up for grabs to anyone who wants to spend a few minutes writing some code that will pass the tests.

2022-11-15 00:48 UTC, Stargator commented
@kytrinyx The sum-of-multiplesexercise is missing the pubspec.yaml file.

2022-11-15 08:38 UTC, kytrinyx commented
@Stargator there's a `pubspec.yaml` file in this PR. Is there a different pubspec that is missing? Or is it in the wrong place?

2022-11-15 12:53 UTC, Stargator commented
> there's a pubspec.yaml file in this PR. Is there a different pubspec that is missing? Or is it in the wrong place?

No, it's fine. I guess I just missed it.

2022-11-24 18:55 UTC, Stargator requested changes
I am working on the solution for this now

2022-11-24 18:55 UTC, Stargator commented on exercises/practice/sum-of-multiples/test/sum_of_multiples_test.dart
> +import 'package:test/test.dart';
This is missing the import from sum_of_multiples.dart.

2022-11-24 19:53 UTC, Stargator commented
@kytrinyx I've implemented a solution and added the missing import in the test suite. I don't know if you want to regenerate the test suite. If not, then this is good.

2022-11-25 11:37 UTC, kytrinyx commented
I don't need to regenerate the test suite (I'll add the import on my end so I have it next time I have to touch the exercise).

I'll add you as author and then get this merged.

Thank you so much for taking the time to implement the solution!

2022-12-01 17:17 UTC, Stargator approved these changes

2022-12-02 07:09 UTC, merged

2022-12-02 07:10 UTC, kytrinyx commented
Thanks @Stargator!