Update ABOUT.md
exercism/dart pull request #596
Opened 2024-10-04 08:50 UTC by hesham04Dev

close #343
updating the about to be up to date

2024-10-07 15:06 UTC, glennj requested changes

2024-10-07 15:06 UTC, glennj commented on docs/ABOUT.md
> +- **Server-Side Capabilities:** Dart is not just for frontend development; it can be used to build scalable server-side applications with frameworks like [Shelf](https://pub.dev/packages/shelf) or th
If it's deprecated then it shouldn't be a "key concept".

2024-10-07 15:06 UTC, glennj commented on docs/ABOUT.md
> +Dart combines object-oriented programming and static typing with the flexibility of dynamic languages like JavaScript. Designed to simplify common programming tasks, Dart has rapidly gained popularit
Please follow the [Exercism Markdown layout standards](https://exercism.org/docs/building/markdown/markdown#h-layout).

2025-01-05 12:43 UTC, kytrinyx commented on docs/ABOUT.md
> +Dart combines object-oriented programming and static typing with the flexibility of dynamic languages like JavaScript. Designed to simplify common programming tasks, Dart has rapidly gained popularit
I went ahead and pushed a commit that uses one sentence per line.

2025-01-06 13:09 UTC, glennj commented on docs/ABOUT.md
> +- **Server-Side Capabilities:** Dart is not just for frontend development; it can be used to build scalable server-side applications with frameworks like [Shelf](https://pub.dev/packages/shelf) or th
Are you going to change this?

2025-01-06 13:28 UTC, kytrinyx commented on docs/ABOUT.md
> +- **Server-Side Capabilities:** Dart is not just for frontend development; it can be used to build scalable server-side applications with frameworks like [Shelf](https://pub.dev/packages/shelf) or th
Sorry, I missed this. Yeah, let me remove that.

2025-01-06 15:11 UTC, glennj approved these changes

2025-01-07 14:08 UTC, merged